FROM java:openjdk-7-jdk

MAINTAINER Andrew Jackson "anj@anjackson.net"

# update packages and install maven
RUN \
  export DEBIAN_FRONTEND=noninteractive && \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y vim wget curl git maven

RUN \
  git clone https://github.com/kermitt2/grobid.git

RUN \
  cd grobid && \
  mvn install -DskipTests

WORKDIR grobid/grobid-service

EXPOSE 8080

ENV JAVA_OPTS -Xmx2g
cp -r grobid-quantities grobid/
cd PATH-TO-GROBID/grobid/grobid-quantities
mvn generate-resources -Ptrain_quantities
mvn generate-resources -Ptrain_units



java -jar target/grobid-quantities-0.4.0-SNAPSHOT.one-jar.jar -gH ../grobid-home/ -gP ../grobid-home/config/grobid.properties -dIn ~/grobid/grobid-quantities/src/test/resources/ -dOut ~/test/ -exe createTrainingQuantities
java -jar target/grobid-quantities-0.4.0-SNAPSHOT.one-jar.jar -gH ../grobid-home/ -gP ../grobid-home/config/grobid.properties
 -dIn input/resources -dOut /tmp/ -exe generateTrainingUnits



cd $GROBID-HOME/grobid/

cd PATH-TO-GROBID/grobid/grobid-quantities
mvn compile test

mvn -Dmaven.test.skip=true clean install
mvn -Dmaven.test.skip=true jetty:run-war

